name: Chris Sainty
author: Chris Sainty
description: A technical blog covering full-stack web development.
markdown: redcarpet
paginate: 5
highlighter: pygments
url: http://blog.csainty.com
tag_page_layout: tag_page
tag_page_dir: tag
rss_post_limit: 10
feed_url: http://blog.csainty.com/rss.xml
excerpt_separator: "<!-- more -->"
