name: Chris Sainty
author: Chris Sainty
description: A technical blog covering full-stack web development.
markdown: redcarpet
paginate: 5
url: https://blog.csainty.com
tag_page_layout: tag_page
tag_page_dir: tag
rss_post_limit: 10
feed_url: https://blog.csainty.com/rss.xml
excerpt_separator: "<!-- more -->"
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag
exclude:
  - Dockerfile
  - publish.sh
  - start.sh
  - .git
  - .asset-cache
  - .DS_Store
assets:
  compress:
    css: true
    js: true
  digest: true
  assets:
    - bundle.css.scss
  sources:
    - _assets/stylesheets
