name: Chris Sainty
author: Chris Sainty
description: A technical blog about software development. Usual topics include C#, Node.js, WP7, RavenDb, Nancy.
markdown: redcarpet
pygments: false
paginate: 5
url: http://blog.csainty.com
tag_page_layout: tag_page
tag_page_dir: tag
rss_post_limit: 10
